
// Do not edit this file, it is automatically generated by Firebase App Studio
export const firebaseConfig = {
  projectId: 'studio-2443742526-bea7a',
  appId: '1:621589016909:web:5443aa58f0b60005784704',
  apiKey: 'AIzaSyA3XIrSuscNIubu0p17D1QuNCCjJZnim5A',
  authDomain: 'studio-2443742526-bea7a.firebaseapp.com',
  measurementId: 'G-551JM7V31P',
  storageBucket: "studio-2443742526-bea7a.appspot.com"
};
