// src/components/icons.tsx

import type { LucideProps } from "lucide-react";
import {
  AlertTriangle,
  Award,
  BookOpen,
  Coffee,
  Gauge,
  History,
  Loader2,
  Menu,
  Milestone,
  Moon,
  Move,
  Pause,
  Phone,
  Play,
  RefreshCw,
  Settings,
  Star,
  Sunrise,
  Timer,
  Trophy,
  Truck,
  Zap,
  Route,
  LogIn,
  LogOut,
  BarChart,
  Gem,
  Map,
  Calculator,
  HeartHandshake,
  Share2,
  Package, // 👈 NUEVO IMPORT
} from "lucide-react";

export const Icons = {
  Truck: (props: LucideProps) => <Truck {...props} />,
  Play: (props: LucideProps) => <Play {...props} />,
  Pause: (props: LucideProps) => <Pause {...props} />,
  Refresh: (props: LucideProps) => <RefreshCw {...props} />,
  Move: (props: LucideProps) => <Move {...props} />,
  Spinner: (props: LucideProps) => <Loader2 {...props} />,
  AlertTriangle: (props: LucideProps) => <AlertTriangle {...props} />,
  Settings: (props: LucideProps) => <Settings {...props} />,
  Menu: (props: LucideProps) => <Menu {...props} />,
  History: (props: LucideProps) => <History {...props} />,
  BookOpen: (props: LucideProps) => <BookOpen {...props} />,
  Award: (props: LucideProps) => <Award {...props} />,
  Speedometer: (props: LucideProps) => <Gauge {...props} />,
  Gauge: (props: LucideProps) => <Gauge {...props} />,
  Milestone: (props: LucideProps) => <Milestone {...props} />,
  Timer: (props: LucideProps) => <Timer {...props} />,
  Star: (props: LucideProps) => <Star {...props} />,
  Trophy: (props: LucideProps) => <Trophy {...props} />,
  Zap: (props: LucideProps) => <Zap {...props} />,
  Sunrise: (props: LucideProps) => <Sunrise {...props} />,
  Moon: (props: LucideProps) => <Moon {...props} />,
  Coffee: (props: LucideProps) => <Coffee {...props} />,
  Route: (props: LucideProps) => <Route {...props} />,
  Login: (props: LucideProps) => <LogIn {...props} />,
  Logout: (props: LucideProps) => <LogOut {...props} />,
  BarChart: (props: LucideProps) => <BarChart {...props} />,
  Premium: (props: LucideProps) => <Gem {...props} />,
  Map: (props: LucideProps) => <Map {...props} />,
  Phone: (props: LucideProps) => <Phone {...props} />,
  Calculator: (props: LucideProps) => <Calculator {...props} />,
  HeartHandshake: (props: LucideProps) => <HeartHandshake {...props} />,
  Share: (props: LucideProps) => <Share2 {...props} />,
  Package: (props: LucideProps) => <Package {...props} />, // 👈 NUEVO ICONO AÑADIDO
};
